import math
from typing import List, Dict
import sys

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from aloha_mpr import simulate

def p_k(k: int, lam: float, time_slot: float) -> float:
    """
    Model the packet arrival as a Bernoulli process with arrival rate. p_k models the probability
    of k packets generated by a user within a slot. This function models equation 1 in the Feng paper

    :param k: The number of packets generated by the user within a slot
    :param lam: the arrival rate of the packets
    :param time_slot: the duration of the slot
    :return: The probability of k packets arriving within the timeslot.
    """
    # if lam * time_slot != 0.1:
    #     print(f"Error: lam*time_slot=({lam})({time_slot}) = {lam * time_slot}. It must be 0.1", file=sys.stderr)
    #     return None

    if k == 0:
        return 1 - (lam * time_slot)
    if k == 1:
        return lam * time_slot
    else:
        print(F"Error: k={k}. It is necessary that k=0|1.", file=sys.stderr)
        return None

def calculate_pi(i:int, lam: float, time_slot: float, pi_vec, p_on: float, p_tr: float, p_s: float, capacity: int) -> float:
    """
    Calculates the steady state probability of some state i where 0 <= i <= I.
    :param p_on: The beam illumination probability
    :param p_tr: The transmission probability
    :param p_s:  The probability of a successful packet transmission
    :param capacity:
    :param i: The desired state
    :param lam: Lambda, the arrival rate of packets
    :param time_slot: Duration of the slot
    :param pi_vec: The vector representing steady-state probabilities
    :return: pi_i, the steady state probability
    """
    p_1 = p_k(1, lam, time_slot)
    p_0 = p_k(0, lam, time_slot)

    arrival_rate = p_1 / (p_0 * p_on * p_tr * p_s)
    alpha = arrival_rate * (1 - p_on * p_tr * p_s)
    alpha_fraction = (1 - math.pow(alpha, capacity)) / (1 - alpha)


    if i == 0:
        denominator = (1 + arrival_rate * alpha_fraction)
        return 1 / denominator
    elif 1 <= i <= capacity:
        return arrival_rate * math.pow(alpha, i - 1) * pi_vec[0]
    else:
        print(f"Error: The steady-state probability for some state may only calculated for i in [0, capacity]", file=sys.stderr)
        return None

def construct_pi_vector(capacity: int, lam: float, time_slot, p_on: float, p_tr: float, p_s: float):
    pi_vector: List[float] = []

    for i in range(0, capacity + 1):
        pi_i = calculate_pi(i, lam,time_slot, pi_vector, p_on, p_tr, p_s, capacity)
        pi_vector.append(pi_i)

    return pi_vector


def calculate_non_empty_probability(pi_0: float):
    """
    Calculates the user queue non-empty probability, p_ex as
    defined in Equation 11 of Feng's paper. Returns the
    probability of there being at least one packet in the
    queue.

    p_ex = 1 - pi_0
    :param pi_0: The steady-state probabilities of the queue model
    :return: p_ex
    """

    return 1 - pi_0


def calculate_probability_of_success(n_m: int, p_ex: float, p_tr: float, n_c: int, n_u: float):
    """
    Calculates the probability of a successful packet transmission (ps).
    The probability of a successful transmission is based on if the number
    of incoming packets in a ground cell is less than the MPR capability of
    the satellite.
    :return: p_s
    """

    ps = 0.0

    """
    The probability that another user contributes another packet
    """
    p = p_ex * p_tr / n_c
    not_p = 1 - p

    for n in range(0, n_m): # n_m is not included
        choose = math.comb(n_u - 1, n)

        ps += choose * math.pow(p, n) * math.pow(not_p, n_u - 1 - n)

    return ps



def algorithm_1(p_on: float=0.4, n_u: int=128, n_c: int=32, n_m: int=3, lam: float=0.1,
                time_slot: float=1, capacity: int=20, p_tr: float=0.4,
                gamma_tar: int = math.pow(10, 2), epsilon: float = math.pow(10, -4)):
    """
    A Numerical Method for computing the steady-state probability of successful packet transmission.
    The algorithm takes in the following parameters and produces:
        - ps: the probability of success
        - pi: the vector representing steady state probability

    :param n_u: The number of users in a single ground cell
    :param n_c: The number of frequency channels
    :param n_m: The multi-packet reception capability of  each serving satellite
    :param lam: The packet arrival rate
    :param time_slot: The duration of each time slot
    :param capacity: (aka I) The buffer capacity (queue length) of each user
    :param p_tr: The probability of transmission under probabilistic beam hopping
    :param p_on: The beam illumination probability under probabilistic beam hopping
    :param gamma_tar:The target value of gamma
    (gamma is the number of iterations to satisfy convergence tolerance)
    :param epsilon: The convergence tolerance. The maximum difference of p_s between two iterations
    :returns Dict[ps, pi_vec]
    """

    gamma: int = 0
    ps: float = 0.001
    pi_vec: list[float] = None
    #pi_ex: float = None

    ps_history: List[int, float] = []

    while gamma < gamma_tar:
        ps_prev:float = ps
        ps_history.append(ps)
        pi_vec =  construct_pi_vector(capacity, lam, time_slot, p_on, p_tr, ps)
        p_ex = calculate_non_empty_probability(pi_vec[0])
        ps = calculate_probability_of_success(n_m, p_ex, p_tr, n_c, n_u)

        if abs(ps_prev - ps) < epsilon:
            gamma += 1
        else:
            gamma = 0


    return {
        'ps': ps,
        'pi': pi_vec,
        'ps_history' : ps_history,
    }

def print_results(results: Dict):
    keys = results.keys()

    for key in list(keys):
        print(f"{key}: {results[key]}")


def generate_ps_iterations_graph(df: pd.DataFrame):
    # graph markers and axes titles
    ax = df.plot(marker='o', ms=3, figsize=(8, 5.5))
    ax.set_xlabel("The number of iterations of Algorithm 1")
    ax.set_ylabel("Steady state $p_s$")
    # axe limits
    ax.set_xlim(0, 120)
    ax.set_ylim(0.4, 1.0)
    ax.grid(0.3)
    # create legend
    ax.legend([f"$p_{{on}}$ = {val}" for val in df.columns])
    plt.tight_layout()
    plt.savefig("fig4a.png",dpi=300)

def plot_curves(data):
    fig, ax = plt.subplots(figsize=(8, 5))

    for key, values in data.items():
        x = [i / 10 for i in range(len(values))]   # index i  ->  x = i/10
        ax.plot(x, values, label=str(key), marker='o')

    ax.set_xlabel("x")
    ax.set_ylabel("y")
    ax.legend(title="Curve")
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()
    return fig, ax



if __name__ == "__main__":




    #p_on_values = [0.2, 0.3, 0.4, 0.5, 0.6]
    p_on_values = np.linspace(0.1, 1.0, 10)
    lam_vals = [0.1, 0.5, 1.0]

    y1 = [algorithm_1(p_on=p, lam=0.01)['ps'] for p in p_on_values]
    y2 = [algorithm_1(p_on=p, lam=0.05)['ps'] for p in p_on_values]
    y3 = [algorithm_1(p_on=p, lam=0.1)['ps'] for p in p_on_values]

    y11 = [simulate(p_on=p,lam=0.01, T=1)[0] for p in p_on_values]
    y21 = [simulate(p_on=p, lam=0.05, T=1)[0] for p in p_on_values]
    y31 = [simulate(p_on=p, lam=0.1, T=1)[0] for p in p_on_values]

    plt.plot(p_on_values, y1, label="analytical lambda=0.01", color="royalblue", linestyle="-")
    plt.plot(p_on_values, y2,label="analytical lambda=0.05", color="darkorange", linestyle="-")
    plt.plot(p_on_values, y3, label="analytical lambda=0.1", color="forestgreen", linestyle="-")

    plt.plot(p_on_values, y11, label="simulated lambda=0.01", color="royalblue", linestyle="dotted")
    plt.plot(p_on_values, y21, label="simulated lambda=0.05", color="darkorange", linestyle="dotted")
    plt.plot(p_on_values, y31, label="simulated lambda=0.1", color="forestgreen", linestyle="dotted")

    # 4. Customize the plot elements
    plt.title("Steady-State Probability of Successful Packet Transmissions")
    plt.xlabel("Analytical $p_{on}$ value")
    plt.ylabel("Steady-State $p_s$")
    plt.grid(True, linestyle=":", alpha=0.6)

    # 5. Display the legend and show the graph
    plt.legend(loc="lower right")
    plt.savefig("steady-state-packet-transmission.png", dpi=300, bbox_inches="tight")




    for val in p_on_values:
        result = algorithm_1(val)
        print(f"p_on={val}")
        print_results(result)

    histories = {}
    for p_on in p_on_values:
        result = algorithm_1(p_on)
        histories[p_on] = pd.Series(result["ps_history"],name=p_on)

    df = pd.DataFrame(histories)
    df.index.name = "iteration"
    generate_ps_iterations_graph(df)

